# Buildpacks to include in builder
[[buildpacks]]
uri = "buildpacks/wildfly"

# Order used for detection
[[order]]
    # This buildpack will display build-time information (as a dependency)
    [[order.group]]
    id = "wildfly/wildfly"
    version = "0.0.1"

# Stack that will be used by the builder
[stack]
id = "org.wildfly.stacks.base"
# run-image and build-image are missing on purpose
# as they will be appended in create-builder.sh
# based on the registry hosting the three images
# (builder, build, run)